# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9435ebd34b7682d9288c3289b00c007eb69f4c06aad2537d4f3836b07ce0cd9a796ef416313fdd723b859ab5ad38ce42098c5cd073c0ffc538d7b18eb9ee92f

test:
  secret_key_base: 86c5464a9c24af507bc32152681e42f097aca9fcf203a1ac0e6d4ab0b7bd2c7efa4d9a2a812c453d630cd74911c4f2101cdf9200c120f21cde19a95b0866eaf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
